name: CI

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3.0.2

      - run: |
          git config --local core.autocrlf true
          git config --local user.name "Microsoft GitHub User"
          git config --local user.email msftgits@microsoft.com

      - run: |
          cd .\tools\v1.0
          .\launch.ps1 > ..\..\defconfig

      - run: |
          git add .
          git commit --message "Update to the latest Microsoft Teams builds"
          git push

      - run: |
          cd .\tools\v2.0
          .\launch.ps1 > ..\..\defconfig2

      - run: |
          git add .
          git commit --message "Update to the latest Microsoft Teams builds"
          git push
